version: "3.8"
services:
  state-proxy:
    container_name: state-proxy
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - WHITELIST=
      - PORT=
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
